### ISSUE TITLE
ctc.train error

### ISSUE THREAD

**Issue by VwakeM** [marco-willi/camera-trap-classifier#16]
I used Option 1 to prepare data for a small dataset of 3 species. When running ctc.train, I get the following error: 

```
c:\users\mallevx\appdata\local\continuum\anaconda3\envs\ctc\lib\site-packages\camera_trap_classifier\config\config.py:19: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  self.cfg = yaml.load(fp)
Traceback (most recent call last):
  File "c:\users\mallevx\appdata\local\continuum\anaconda3\envs\ctc\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mallevx\appdata\local\continuum\anaconda3\envs\ctc\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mallevx\AppData\Local\Continuum\anaconda3\envs\ctc\Scripts\ctc.train.exe\__main__.py", line 9, in <module>
  File "c:\users\mallevx\appdata\local\continuum\anaconda3\envs\ctc\lib\site-packages\camera_trap_classifier\train.py", line 330, in main
    zip(output_labels, output_labels_clean)}
  File "c:\users\mallevx\appdata\local\continuum\anaconda3\envs\ctc\lib\site-packages\camera_trap_classifier\train.py", line 329, in <dictcomp>
    for o, c in
KeyError: 'species'
```

**My ctc.train command:** 

`ctc.train -train_tfr_path C:/Users/mallevx/ctc/tfr/ -val_tfr_path C:/Users/mallevx/ctc/tfr/ -test_tfr_path C:/Users/mallevx/ctc/tfr/ -class_mapping_json C:/Users/mallevx/ctc/tfr/label_mapping.json -run_outputs_dir C:/Users/mallevx/ctc/my_model/run1/ -model_save_dir C:/Users/mallevx/ctc/my_model/save1/ -model ResNet18 -labels species count -labels_loss_weights 1 0.5 -batch_size 128 -n_cpus 4 -n_gpus 1 -buffer_size 512 -max_epochs 70`

**Contents of my label_mapping.json:** 
`{"class": {"BADGER_1": 0, "BEAVER_1": 1, "MINK_1": 2}}`

Any thoughts on what's wrong? Thanks in advance!

**Comment by marco-willi** [comment]
Hi Vivek, 

Thanks for bringing this to my attention. The issue is this:
```
-labels species count
-labels_loss_weights 1 0.5
```
If you create a dataset inventory from class directories (option 1), the default label name will be 'class' (since you could train your model to identify any type of classes). My apologies for not documenting that appropriately. To fix the issue simply use:

```
-labels class
```
(labels_loss_weights have no effect if you only have one label)

If, in fact, you have more data about your images (like counts of animals) you would have to use a csv file (option 2) to prepare a dataset inventory if you want to model species and counts at the same time. Additionally, if your dataset is very small (<128 images) you may want to decrease the batch size.

I have updated the documentation and pointed to a small example that is in the description about how to use Docker.

Let me know if you have more questions!

**Comment by VwakeM** [comment]
Thanks, Marco. Appreciate your quick response and the documentation is easy to follow along. I will be use the csv option next. At present, my goal is ensure my set-up works fine. 

My updated command looks like this: 

`ctc.train -train_tfr_path C:/Users/mallevx/ctc/tfr/ -val_tfr_path C:/Users/mallevx/ctc/tfr/ -test_tfr_path C:/Users/mallevx/ctc/tfr/ -class_mapping_json C:/Users/mallevx/ctc/tfr/label_mapping.json -run_outputs_dir C:/Users/mallevx/ctc/my_model/run1/ -model_save_dir C:/Users/mallevx/ctc/my_model/save1/ -model ResNet18 -labels class -batch_size 128 -n_cpus 4 -buffer_size 512 -max_epochs 70`

I was also using the GPU option while I none on my laptop, so I took that out. I get a different error message now: 

`Traceback (most recent call last):
  File "c:\users\mallevx\appdata\local\continuum\anaconda3\envs\ctc\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\mallevx\appdata\local\continuum\anaconda3\envs\ctc\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\mallevx\AppData\Local\Continuum\anaconda3\envs\ctc\Scripts\ctc.train.exe\__main__.py", line 9, in <module>
  File "c:\users\mallevx\appdata\local\continuum\anaconda3\envs\ctc\lib\site-packages\camera_trap_classifier\train.py", line 566, in main
    initial_epoch=args['starting_epoch'])
  File "c:\users\mallevx\appdata\local\continuum\anaconda3\envs\ctc\lib\site-packages\tensorflow\python\keras\engine\training.py", line 1639, in fit
    validation_steps=validation_steps)
  File "c:\users\mallevx\appdata\local\continuum\anaconda3\envs\ctc\lib\site-packages\tensorflow\python\keras\engine\training_arrays.py", line 239, in fit_loop
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "c:\users\mallevx\appdata\local\continuum\anaconda3\envs\ctc\lib\site-packages\tensorflow\python\keras\callbacks.py", line 214, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "c:\users\mallevx\appdata\local\continuum\anaconda3\envs\ctc\lib\site-packages\camera_trap_classifier\training\hooks.py", line 97, in on_epoch_end
    filepath = self.filepath.format(epoch=epoch + 1, **logs)
KeyError: 'val_loss'`

Any thoughts?

**Comment by marco-willi** [comment]
It looks like Keras was not able to calculate a validation loss.  I suspect the reason may be the (small) size of your dataset and the fact that any records (batch remainders) that do not fit into one batch are dropped. I forgot to mention that batch_size should also be smaller than the smallest dataset (test / train / validation) -- this is normally not an issue because training models with such small datasets is rather pointless, but obviously for testing it makes sense.  If my suspicion is correct reducing batch_size should work, for example:

```
-batch_size 4
```

**Comment by VwakeM** [comment]
That worked! And, I was able to run the predict command as well. So, I think I am good set-up wise.

Thanks for your support, especially on a Sunday :).
