### ISSUE TITLE
predict with pre-trained models

### ISSUE THREAD

**Issue by matobler** [marco-willi/camera-trap-classifier#18]
I am trying to use the pre-trained models that were published with your paper to predict on our own data from Kenya. For now I am using the ss_blank_vs_non_blank_small_201711150811.hdf5 model. I created the following .json files:

class_mapping_blanks.json
```{"class": {"0": "blank", "1": "non_blank"}}```

pre_processing_blank.json
```{"output_height": 224,"output_width": 224,"image_means": [0.16718366742134094, 0.16718366742134094, 0.16718366742134094],"image_stdevs": [0.2730404734611511, 0.2891225218772888, 0.2891225218772888],"is_training": 0,"image_choice_for_sets": "random"}```

and use the following command:
```ctc.predict -image_dir T:\Kenya\Test_Photos_Small -results_file T:\KenyaPred.csv  -model_path "T:\Willi Code\models\ss\ss_blank_vs_non_blank_small_201711150811.hdf5"  -class_mapping_json "T:\Willi Code\models\ss\class_mapping_blanks.json"  -pre_processing_json "T:\Willi Code\models\ss\pre_processing_blank.json" -batch_size 32```

Things initially look good;

```
Arg: csv_path, Value:None
Arg: csv_images_root_path, Value:
Arg: csv_id_col, Value:
Arg: csv_images_cols, Value:['']
Arg: image_dir, Value:T:\Kenya\Test_Photos_Small
Arg: results_file, Value:T:\KenyaPred.csv
Arg: export_file_type, Value:csv
Arg: model_path, Value:T:\Willi Code\models\ss\ss_blank_vs_non_blank_small_201711150811.hdf5
Arg: class_mapping_json, Value:T:\Willi Code\models\ss\class_mapping_blanks.json
Arg: pre_processing_json, Value:T:\Willi Code\models\ss\pre_processing_blank.json
Arg: batch_size, Value:32
Arg: aggregation_mode, Value:mean
2019-04-10 12:08:44.183003: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-04-10 12:08:44.882380: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1432] Found device 0 with properties:
name: Quadro M2000M major: 5 minor: 0 memoryClockRate(GHz): 1.137
pciBusID: 0000:01:00.0
totalMemory: 4.00GiB freeMemory: 3.34GiB
2019-04-10 12:08:44.891074: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-04-10 12:08:45.955152: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-04-10 12:08:45.961057: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0
2019-04-10 12:08:45.966280: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N
2019-04-10 12:08:45.969242: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 3055 MB memory) -> physical GPU (device: 0, name: Quadro M2000M, pci bus id: 0000:01:00.0, compute capability: 5.0)
Read following class mappings:
  Reading values for entry: class
    Key: 0 - Value: blank
    Key: 1 - Value: non_blank
Read following pre processing options:
  Key: output_height - Value: 224
  Key: output_width - Value: 224
  Key: image_means - Value: [0.16718366742134094, 0.16718366742134094, 0.16718366742134094]
  Key: image_stdevs - Value: [0.2730404734611511, 0.2891225218772888, 0.2891225218772888]
  Key: is_training - Value: 0
  Key: image_choice_for_sets - Value: random
```

but then I get the following error:

```
Traceback (most recent call last):
  File "c:\program files\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\program files\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python36\Scripts\ctc.predict.exe\__main__.py", line 9, in <module>
  File "c:\program files\python36\lib\site-packages\camera_trap_classifier\predict.py", line 92, in main
    batch_size=args['batch_size'])
  File "c:\program files\python36\lib\site-packages\camera_trap_classifier\predicting\predictor.py", line 103, in predict_from_image_dir
    batch_size, export_type)
  File "c:\program files\python36\lib\site-packages\camera_trap_classifier\predicting\predictor.py", line 294, in _predict_inventory
    sub_preds = self._iterate_inventory_dataset(dataset, sub_inventory)
  File "c:\program files\python36\lib\site-packages\camera_trap_classifier\predicting\predictor.py", line 378, in _iterate_inventory_dataset
    self.processor.map_and_extract_model_prediction(_id_preds)
  File "c:\program files\python36\lib\site-packages\camera_trap_classifier\predicting\processor.py", line 24, in map_and_extract_model_prediction
    list(self.id_to_class_mapping_clean[output].keys())
KeyError: 'dense_1'
```

which is in the code that maps the model output to the classes. I can load the model into my own Keras code and make predictions that way, so the model is fine.  Any suggestions would be welcome.

**Comment by marco-willi** [comment]
Hi Mathias,

Thanks for raising this important issue. I hope to have a few suitable solutions for you to resolve this. First of all: The models that I have published were created using a different version of the code that is (unfortunately) not compatible with the new code. The publication-code is a bit 'hacky' thus the new implementation. I have not (yet) published any models trained with the new 'camera-trap-classifier' code -- understandably, this is not ideal. There are two solutions for you:

1. You can use the 'publication-code' to run the models and follow the 'Apply Models' section: [camera-trap-classifier-publication-code](https://github.com/marco-willi/camera-trap-classifier-publication-code)
2. I have trained two new models on a much larger dataset that I intend to link to this GitHub repo soon. This might be 1-4 weeks out. These will be one 'empty or not' model, and one large 'species' model. These models have seen a variety of species, mainly from Tanzania and South Africa. 
3. If you can't wait for 2) I'm more than happy to upload the 'empty or not' model to share it with you -- just let me know your e-mail.

Generally: If you're only interested in applying the published model on new data then 1) is a suitable solution. If you want a better model, or want to use a model to train your own model (transfer-learning) I'd definitely use the new code. 

Best, Marco

**Comment by matobler** [comment]
Hi Marco,

thanks for the quick response. The old code works great. I did not realize there was another repo for this. I am currently running the old models but will definitely be interested in trying the new models. We run the Wildwatch Kenya Zooniverse site so I hope your pre-trained models from SS will work to ID most of our species. It will definitely be an interesting test. I currently have 125k tagged images we can test the models on. I might be in touch by emails to discuss this some more.

Best,

Mathias
